name: CMake

on:
  push:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        abi: ["x86_64", "arm64-v8a", "x86", "armeabi-v7a" ]
        include:
        - abi: armeabi-v7a
          openssltarget: android-armeabi
        - abi: arm64-v8a
          openssltarget: android-arm64
    steps:
    - uses: actions/checkout@v2
    - uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r21e
        add-to-path: false
    - uses: actions/checkout@v2
      with:
        repository: "openssl/openssl"
        ref: OpenSSL_1_1_1-stable
        path: openssl
        
    - name: Configure and build Openssl
      run: |
        export PATH="$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/:$PATH"
        ./Configure ${{ matrix.openssltarget || format('android-{0}', matrix.abi) }} && make install_runtime_libs 
      env:
        ANDROID_NDK_ROOT: ${{ steps.setup-ndk.outputs.ndk-path }}
      working-directory: ${{github.workspace}}/openssl
      
    - uses: actions/checkout@v2
      with:
        repository: "protocolbuffers/protobuf"
        ref: 3.18.x
        path: protobuf
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/buildprotobuf -S protobuf/cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE=${{ steps.setup-ndk.outputs.ndk-path }}/build/cmake/android.toolchain.cmake -DANDROID_ABI=${{ matrix.abi }}
    - name: Build Protobuf
      run: cmake --build ${{github.workspace}}/buildprotobuf --config ${{env.BUILD_TYPE}}
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE=${{ steps.setup-ndk.outputs.ndk-path }}/build/cmake/android.toolchain.cmake -DANDROID_ABI=${{ matrix.abi }} -DProtobuf_SRC_ROOT_FOLDER=${{github.workspace}}/protobuf/src -DProtobuf_INCLUDE_DIR=${{github.workspace}}/protobuf/src -DProtobuf_PROTOC_EXECUTABLE=${{github.workspace}}/buildprotobuf/protoc -DProtobuf_LIBRARY=${{github.workspace}}/buildprotobuf/cmake/libprotobuf.so) -DOPENSSL_SSL_LIBRARY=${{github.workspace}}/openssl/libssl.so -DOPENSSL_CRYPTO_LIBRARY=${{github.workspace}}/openssl/libcrypto.so -DOPENSSL_CRYPTO_LIBRARY=${{github.workspace}}/openssl/include
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

  
      
